# Generated by Django 5.0.3 on 2024-04-17 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_info'),
    ]

    operations = [
        migrations.RenameField(
            model_name='info',
            old_name='instagram',
            new_name='tiktok',
        ),
        migrations.AddField(
            model_name='info',
            name='youtube',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
