# Generated by Django 5.0.3 on 2024-04-15 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_blog_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='view',
        ),
    ]
