# Generated by Django 5.0.3 on 2024-04-17 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_contact_address_contact_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='instagram',
            field=models.CharField(default=11, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='info',
            name='address',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='info',
            name='telegram',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='info',
            name='tiktok',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='info',
            name='youtube',
            field=models.CharField(max_length=255),
        ),
    ]
