# Generated by Django 5.0.3 on 2024-04-20 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_info_instagram_alter_info_address_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='About',
        ),
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
