# Generated by Django 5.0.3 on 2024-04-20 13:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_delete_about_delete_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Checkout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.TextField()),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=13, validators=[django.core.validators.RegexValidator(code='Telefon raqam xato', message="Telefon raqamingizni to'g'ri ko'rsating.", regex='^[\\+]9{2}8{1}[0-9]{9}$')])),
                ('country', models.CharField(max_length=255)),
                ('quantity', models.IntegerField(default=1)),
            ],
        ),
        migrations.DeleteModel(
            name='Order',
        ),
    ]
