# Generated by Django 5.0.3 on 2024-04-22 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_checkout_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='description_en',
            field=models.CharField(max_length=55, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='description_ru',
            field=models.CharField(max_length=55, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='description_uz',
            field=models.CharField(max_length=55, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='text_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='text_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='text_uz',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='title_en',
            field=models.CharField(max_length=55, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='title_ru',
            field=models.CharField(max_length=55, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='title_uz',
            field=models.CharField(max_length=55, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='description_en',
            field=models.CharField(max_length=55, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='description_ru',
            field=models.CharField(max_length=55, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='description_uz',
            field=models.CharField(max_length=55, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='text_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='text_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='text_uz',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='title_en',
            field=models.CharField(max_length=55, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='title_ru',
            field=models.CharField(max_length=55, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='title_uz',
            field=models.CharField(max_length=55, null=True),
        ),
    ]
